server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # SPA: route inconnue → index.html
  location / {
    try_files $uri $uri/ /index.html;
  }
  # NOTE: en prod, ajouter ici un `location /api/ { proxy_pass http://<backend-nestjs>; }`
  # (backend = repo nest-dashflow-app) — à finaliser à l'étape déploiement.
}
